## all()
- 参数
	- `iterable`
- 返回值
	- 若所有promise都成功，返回成功
	- 若有一个promise失败，返回失败
```js
Promise.all([promise1, promise2, promise3])
	.then(values => {alert(values)})
```
## race()
- 参数
	- `iterable`
- 返回值
	- 若有一个promise成功，返回第一个成功的promise的值
	- 若有一个promise失败，返回第一个失败的promise的值
```js
Promise.race([promise1, promise2, promise3])
	.then(value => {alert(value)})
```
## reject()
- 参数
	- `reason`：拒绝的原因
- 返回值
	- `promise`：rejected promise
```js
const resolved = () => {console.log('resolved')}
const rejected = () => {console.log('rejected')}

Promise.reject().then(resolved, rejected) // 'rejected'
```
## resolve()
- 参数
	- `value`：解析值，也可以是 `promise` 或 `thenable`
- 返回值
	- `promise`：resolved promise
```js
Promise.resolve(123)
	.then(value => {console.log(value)}) // 123
```
## then()
- 参数
	- `onFulfilled?`：`fulfilled` 状态的回调函数
		- `fulfillment value`：
	- `onRejected?`：`rejected` 状态的回调函数
		- `rejection reason`：
- 返回值：`Promise`
```js
const resolved = () => {console.log('resolved')}
const rejected = () => {console.log('rejected')}

Promise.reject().then(resolved, rejected) // 'rejected'
```
## catch()
- 效果：`Promise.then(undefined, onRejected)` 的简写
```js
const rejected = () => {console.log('rejected')}

Promise.reject().catch(rejected) // 'rejected'
```
## finally()
- 效果：无论结果是 `fulfilled` 或者是 `rejected`，都会执行指定的回调函数
```js
Promise.finally(onFinally)
```